[package]
name = "magnus_carlsen_scraper"
version = "0.1.0"
authors = ["mdrokz <mohammadmunshi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = '0.14.2'
serde_json = '1.0.60'

[dependencies.tokio]
version = "0.2.22"
features = ["macros"]